peer:
  minConnections: 5
  maxConnections: 10
  bootstraps:
    - '127.0.0.1:5000'
  peerAddr: '127.0.0.1:6000'
  apiAddr: '127.0.0.1:7000'
  knownPeers:
    - '127.0.0.1:6001'
gossip:
  cacheSize: 100
  degree: 10




